export const javascript = [
	'JavaScript is the language of the web - embrace it!',
	"Write once, run everywhere - that's the power of JavaScript.",
	"In JavaScript, there's always another way to do it.",
	'From DOM manipulation to animation, JavaScript does it all.',
	'JavaScript: the backbone of modern web development.',
	'With JavaScript, you can create anything you can imagine.',
	'JavaScript - the duct tape of web development.',
	'In JavaScript, the possibilities are endless.',
	'From frontend to backend, JavaScript is the way to go.',
	'JavaScript is to web development what electricity is to modern life.',
	'JavaScript - the language that powers interactivity on the web.',
	'JavaScript is easy to learn, but hard to master.',
	'JavaScript - making the web more interactive, one line of code at a time.',
	'JavaScript is the key to creating responsive, dynamic web experiences.',
	'JavaScript - the foundation of modern web applications.',
	'With JavaScript, you can turn static web pages into living, breathing experiences.',
	"JavaScript is constantly evolving - there's always something new to learn.",
	'JavaScript - bridging the gap between design and development.',
	'In JavaScript, every problem has a solution - you just have to find it.',
	'JavaScript - the most widely used programming language on the planet.',
];

export const css = [
	'CSS is the visual language of the web.',
	'CSS is the styling glue that holds the web together.',
	'Without CSS, the web would be a dull, unstyled place.',
	'CSS lets you make your website look exactly how you want it to.',
	'With CSS, you can create stunning, responsive designs that look great on any device.',
	'CSS is the paintbrush for the web designer.',
	'CSS is the finishing touch that brings a website to life.',
	'CSS is a powerful tool for expressing your creativity.',
	'CSS is the magic that transforms plain HTML into beautiful web pages.',
	'CSS is the key to creating a consistent, cohesive visual style for your website.',
	'With CSS, you can create complex layouts and designs with ease.',
	'CSS makes it easy to create dynamic and interactive user interfaces.',
	'CSS is the Swiss Army Knife of web design.',
	'CSS lets you create elegant and sophisticated designs without writing a lot of code.',
	'CSS is the foundation of modern web design.',
	'CSS is a language that every web developer should know.',
	'CSS is an essential tool for any web designer.',
	'CSS lets you create beautiful, functional websites quickly and easily.',
	'CSS gives your website its personality and style.',
	'CSS is constantly evolving and improving, making it an exciting area to work in.',
];

export const java = [
	'Java is the foundation of many enterprise applications.',
	'Java is one of the most popular programming languages in the world.',
	'Java makes it easy to write powerful, cross-platform applications.',
	'Java is an object-oriented programming language with a simple syntax.',
	'Java is a powerful tool for building large-scale, complex systems.',
	'Java is designed to be secure and robust.',
	'Java is a popular choice for building mobile applications.',
	'Java is a mature language with a vast ecosystem of libraries and tools.',
	'Java has a large community of developers and users who contribute to its growth and improvement.',
	'Java is a versatile language that can be used for web, desktop, and mobile applications.',
	'Java is constantly evolving to meet the needs of modern developers.',
	'Java is used by some of the largest companies in the world, including Google, Amazon, and Netflix.',
	'Java is a language that can be learned quickly, but takes years to master.',
	'Java is a popular choice for building high-performance applications.',
	'Java is a language that emphasizes code readability and maintainability.',
	'Java is a great language for beginners because of its simple syntax.',
	'Java is a language that emphasizes developer productivity.',
	'Java is a language that is widely used in the scientific and academic communities.',
	'Java is a language that emphasizes code portability.',
	'Java is a language that is used to build some of the most complex and sophisticated systems in the world.',
];

export const maths = [
	'Mathematics is the language in which God has written the universe. - Galileo Galilei',
	'Pure mathematics is, in its way, the poetry of logical ideas. - Albert Einstein',
	'Mathematics is not about numbers, equations, computations, or algorithms: it is about understanding. - William Paul Thurston',
	'Mathematics is the music of reason. - James Joseph Sylvester',
	'Mathematics is the queen of the sciences. - Carl Friedrich Gauss',
	'Mathematics is the art of giving the same name to different things. - Henri Poincare',
	'Mathematics is the science of patterns. - Keith Devlin',
	'Mathematics is the science which draws necessary conclusions. - Benjamin Peirce',
	'Mathematics is the study of the properties and relationships of abstract entities. - Robert Langlands',
	'Mathematics is the most beautiful and most powerful creation of the human spirit. - Stefan Banach',
	'Mathematics is the key and door to the sciences. - Galileo Galilei',
	'Mathematics is the study of analogies between analogies. - Stefan Banach',
	'In mathematics, the art of proposing a question must be held of higher value than solving it. - Georg Cantor',
	'The study of mathematics, like the Nile, begins in minuteness but ends in magnificence. - Charles Caleb Colton',
	'The essence of mathematics is not to make simple things complicated, but to make complicated things simple. - S. Gudder',
	'Mathematics is the science of the infinite. - Henri Poincare',
	'Mathematics is the most powerful weapon you can use to change the world. - Nelson Mandela',
	'Mathematics is the study of structure, and structure pervades everything we do. - Jeremy Gray',
	'Mathematics is not a careful march down a well-cleared highway, but a journey into a strange wilderness, where the explorers often get lost. - W.S. Anglin',
	'Mathematics, rightly viewed, possesses not only truth, but supreme beauty. - Bertrand Russell',
];

export const php = [
	'PHP is a minor evil perpetrated and created by incompetent amateurs, whereas Perl is a great and insidious evil, perpetrated by skilled but perverted professionals. - Jon Ribbens',
	'PHP is a minor evil perpetrated and created by incompetent amateurs, whereas Perl is a great and insidious evil, perpetrated by skilled but perverted professionals. - Jon Ribbens',
	'PHP is a programming language for people who want to get things done quickly. - Rasmus Lerdorf',
	"PHP is about as exciting as your toothbrush. You use it every day, it does the job, it is a simple tool, it is reliable, you don't think much about it and it just works. - Jack D. Herrington",
	'PHP is one of the cornerstones of web development and something every web developer should know. - David Walsh',
	'PHP is a great tool for building a website, but it is not the only tool. - Elizabeth Naramore',
	'PHP is a language that is popular among web developers, but it is not without its flaws. - Eli White',
	'PHP is not a language that encourages beautiful code. It is a language that encourages getting the job done. - Rasmus Lerdorf',
	'PHP is a server-side language that is used to power many websites and web applications. - David Walsh',
	'PHP is a language that is often derided for being insecure, but the truth is that it is only insecure if you write insecure code. - Eli White',
	'PHP is a great language for beginners because it is easy to learn and has a lot of built-in functionality. - David Walsh',
	'PHP is like a cockroach. It just keeps going and going and going, no matter how much you try to kill it. - Anonymous',
	'PHP is like the duct tape of the internet. It may not be pretty, but it gets the job done. - Anonymous',
	'PHP is not a language for the faint of heart. It is a language for those who are willing to get their hands dirty and dive into the code. - Rasmus Lerdorf',
	'PHP is not a language that you should be using for complex applications. It is a language that you should be using for simple applications. - Eli White',
	'PHP is like a Swiss Army knife. It has a lot of tools, but they are not always the best tools for the job. - Elizabeth Naramore',
	'PHP is a language that has been around for a long time and will continue to be around for a long time to come. - David Walsh',
	'PHP is a language that is often misunderstood. It is not a bad language, it is just a language that is often used badly. - Eli White',
	'PHP is a language that is often used by beginners, but it is also used by some of the largest websites in the world. - David Walsh',
	'PHP is a language that is often criticized, but it is a language that gets the job done. - Elizabeth Naramore',
];

export const physics = [
	'The universe is full of magical things patiently waiting for our wits to grow sharper.',
	'Physics is imagination in a straightjacket.',
	'The most incomprehensible thing about the universe is that it is comprehensible.',
	'All science is either physics or stamp collecting.',
	"Physics isn't the most important thing. Love is.",
	'The universe begins to look more like a great thought than like a great machine.',
	'It is not the answer that enlightens, but the question.',
	'Everything is theoretically impossible, until it is done.',
	"If you can't explain it simply, you don't understand it well enough.",
	'I am enough of an artist to draw freely upon my imagination. Imagination is more important than knowledge. Knowledge is limited. Imagination encircles the world.',
	'The most beautiful thing we can experience is the mysterious. It is the source of all true art and science.',
	'I think I can safely say that nobody understands quantum mechanics.',
	'Nature uses only the longest threads to weave her patterns, so that each small piece of her fabric reveals the organization of the entire tapestry.',
	'Not only is the universe stranger than we imagine, it is stranger than we can imagine.',
	'Science without religion is lame, religion without science is blind.',
	'What we observe is not nature itself, but nature exposed to our method of questioning.',
	"In physics, you don't have to go around making trouble for yourself - nature does it for you.",
	'The important thing is not to stop questioning. Curiosity has its own reason for existing.',
	'The universe seems neither benign nor hostile, merely indifferent.',
	'We are just an advanced breed of monkeys on a minor planet of a very average star. But we can understand the universe. That makes us something very special.',
];

export const python = [
	"Python is an experiment in how much freedom programmers need. Too much freedom and nobody can read another's code; too little and expressiveness is endangered.",
	'Python is a high-level programming language, and one of the easiest languages to learn.',
	'Python is the second best programming language for anything, after Lisp.',
	'Python is a wonderful, dynamic, object-oriented language that can be used for many kinds of software development.',
	'Python is a great language for beginning programmers, but it also has the power and flexibility to run major websites like Pinterest and Dropbox.',
	'Python is a language that is designed to be easy to read and write, while still being powerful and expressive.',
	'Python is often praised for its simplicity, ease of use, and readability.',
	'Python is a programming language that is powerful, expressive, and easy to learn.',
	'Python is an excellent first programming language for new programmers.',
	'Python is a general-purpose programming language that can be used for a wide variety of tasks.',
	'Python is an interpreted, high-level, general-purpose programming language.',
	'Python is a language that can be used for web development, data analysis, machine learning, and more.',
	'Python is a language that is easy to learn, but powerful enough to handle complex tasks.',
	'Python is a great choice for beginners and experts alike, thanks to its simple syntax and powerful features.',
	'Python is a language that is easy to read and write, making it a great choice for beginners.',
	'Python is a language that is widely used in scientific computing, data analysis, and machine learning.',
	'Python is a language that is used by many companies and organizations, including Google, NASA, and the CIA.',
	'Python is a language that is designed to be easy to learn and use, even for people with little or no programming experience.',
	'Python is a language that is well-suited for a wide variety of programming tasks, from simple scripts to complex web applications.',
	'Python is a language that is known for its simplicity and elegance, making it a popular choice among programmers.',
];

export const ruby = [
	'Ruby is designed for programmer happiness.',
	'Ruby is simple in appearance, but is very complex inside, just like our human body.',
	'Ruby is a language that puts a premium on developer productivity.',
	'Ruby is a language that is easy to learn and read, making it a great choice for beginners.',
	'Ruby is a language that emphasizes convention over configuration.',
	'Ruby is a language that is optimized for developer happiness and productivity.',
	'Ruby is a language that is well-suited for web development, scripting, and automation.',
	'Ruby is a language that is known for its expressive syntax and object-oriented features.',
	'Ruby is a language that is often praised for its readability and ease of use.',
	'Ruby is a language that is designed to make programming more enjoyable.',
	'Ruby is a language that is often compared to poetry because of its elegant syntax.',
	'Ruby is a language that is used by many popular web applications, including Twitter, GitHub, and Shopify.',
	'Ruby is a language that is well-suited for agile development and test-driven development.',
	'Ruby is a language that is known for its powerful meta-programming capabilities.',
	'Ruby is a language that is designed to be easy to read and write, making it a great choice for beginners.',
	'Ruby is a language that is optimized for building applications quickly and efficiently.',
	'Ruby is a language that emphasizes code readability and maintainability.',
	'Ruby is a language that is often described as a pleasure to work with.',
	'Ruby is a language that is well-suited for building complex web applications.',
	'Ruby is a language that is designed to be fun to use, while still being powerful and flexible.',
];

export const rust = [
	'Rust is a systems programming language that runs blazingly fast, prevents segfaults, and guarantees thread safety.',
	'Rust is a language that is designed for performance, safety, and concurrency.',
	'Rust is a language that combines the low-level control of C with the high-level abstractions of modern programming languages.',
	'Rust is a language that is focused on safety and correctness, making it a great choice for systems programming.',
	'Rust is a language that empowers developers to write safe and efficient code.',
	'Rust is a language that is designed for building reliable and efficient software.',
	'Rust is a language that is well-suited for concurrent programming, making it ideal for building scalable systems.',
	'Rust is a language that is gaining popularity among developers for its performance and safety features.',
	'Rust is a language that offers memory safety without a garbage collector.',
	'Rust is a language that provides fine-grained control over memory management.',
	'Rust is a language that is designed to prevent common programming errors, such as null pointer dereferencing and buffer overflows.',
	'Rust is a language that is designed to be easy to learn, even for beginners.',
	'Rust is a language that is actively developed and supported by a vibrant community.',
	'Rust is a language that is well-suited for building high-performance web applications.',
	'Rust is a language that offers a modern, expressive syntax that is easy to read and write.',
	'Rust is a language that is designed to be scalable, making it a great choice for building large-scale systems.',
	'Rust is a language that offers powerful abstractions that make it easy to write complex code.',
	'Rust is a language that is designed to be platform-independent, making it a great choice for building cross-platform applications.',
	'Rust is a language that is constantly evolving and improving, with new features and capabilities being added all the time.',
	'Rust is a language that is designed to be fast, reliable, and safe, making it a great choice for building critical systems.',
];

export const zig = [
	'Zig is a general-purpose programming language and toolchain designed for robustness, optimality, and maintainability.',
	'Zig is a programming language that is easy to learn, yet powerful enough to tackle complex problems.',
	'Zig is a language that is designed for performance, safety, and simplicity.',
	'Zig is a language that prioritizes developer productivity and ease-of-use.',
	'Zig is a language that provides advanced features such as compile-time reflection and type inference.',
	'Zig is a language that aims to eliminate common programming errors through strong typing and memory safety.',
	'Zig is a language that provides built-in concurrency primitives for efficient multi-threaded programming.',
	'Zig is a language that is designed for cross-platform development, allowing you to build applications that run on Windows, Linux, macOS, and more.',
	'Zig is a language that provides low-level control over memory allocation, making it a great choice for systems programming.',
	'Zig is a language that provides powerful debugging and profiling tools, making it easy to diagnose and fix issues in your code.',
	'Zig is a language that supports metaprogramming, allowing you to generate code at compile-time and customize the language to your needs.',
	'Zig is a language that provides a modern, expressive syntax that is easy to read and write.',
	'Zig is a language that encourages good programming practices such as unit testing and documentation.',
	'Zig is a language that is constantly evolving and improving, with new features and capabilities being added all the time.',
	'Zig is a language that is designed to be compatible with existing C code, making it easy to integrate with existing systems.',
	'Zig is a language that provides a comprehensive standard library with support for common data structures and algorithms.',
	'Zig is a language that is designed to be efficient, making it a great choice for building high-performance applications.',
	'Zig is a language that provides first-class support for error handling, making it easy to write robust and reliable code.',
	'Zig is a language that is open-source and community-driven, with a vibrant community of developers and contributors.',
	'Zig is a language that is well-suited for building large-scale applications, thanks to its support for modularity and code reuse.',
];
