name: Create GoLang Story
description: Add this story to the list
title: "Your Story Title"
labels: ["metaphore", "golang"]
assignees: ["darkterminal", "mkubdev"]
body:
    - type: markdown
      attributes:
          value: "**Share the current and relevant details**"
    - type: textarea
      id: golang-title
      attributes:
          label: The Backstory about your GoLang Metaphor
          placeholder: "hint: describe the backstory about your golang metaphor"
      validations:
          required: true
    - type: textarea
      id: golang-content
      attributes:
          label: The GoLang Story!
          placeholder: "hint: This is about how I write my GoLang story"
      validations:
          required: true
    - type: input
      id: golang-link
      attributes:
          label: A GoLang demo/repos link
          placeholder: "e.g.: https://github.com.com/username/my-repos"
    - type: input
      id: golang-donation-link
      attributes:
          label: PayPal Link for Donation (GoLang Storyteller)
          placeholder: "e.g.: https://www.paypal.me/your-paypal-profile-username"
