name: Create Rust Story
description: Add this story to the list
title: "Your Story Title"
labels: ["metaphore", "rust"]
assignees: ["darkterminal", "mkubdev"]
body:
    - type: markdown
      attributes:
          value: "**Share the current and relevant details**"
    - type: textarea
      id: rust-title
      attributes:
          label: The Backstory about your Rust Metaphor
          placeholder: "hint: describe the backstory about your Rust metaphor"
      validations:
          required: true
    - type: textarea
      id: rust-content
      attributes:
          label: The Rust Story!
          placeholder: "hint: This is about how I write my Rust story"
      validations:
          required: true
    - type: input
      id: rust-link
      attributes:
          label: A Rust demo/repos link
          placeholder: "e.g.: https://github.com.com/username/my-repos"
    - type: input
      id: rust-donation-link
      attributes:
          label: PayPal Link for Donation (Rust Storyteller)
          placeholder: "e.g.: https://www.paypal.me/your-paypal-profile-username"
