name: Create Zig Story
description: Add this story to the list
title: "Your Story Title"
labels: ["metaphore", "zig"]
assignees: ["darkterminal", "mkubdev"]
body:
    - type: markdown
      attributes:
          value: "**Share the current and relevant details**"
    - type: textarea
      id: zig-title
      attributes:
          label: The Backstory about your Zig Metaphor
          placeholder: "hint: describe the backstory about your Zig metaphor"
      validations:
          required: true
    - type: textarea
      id: zig-content
      attributes:
          label: The Zig Story!
          placeholder: "hint: This is about how I write my Zig story"
      validations:
          required: true
    - type: input
      id: zig-link
      attributes:
          label: A Zig demo/repos link
          placeholder: "e.g.: https://github.com.com/username/my-repos"
    - type: input
      id: zig-donation-link
      attributes:
          label: PayPal Link for Donation (Zig Storyteller)
          placeholder: "e.g.: https://www.paypal.me/your-paypal-profile-username"
