name: Create Physics Story
description: Add this story to the list
title: "Your Story Title"
labels: ["metaphore", "physics"]
assignees: ["darkterminal", "mkubdev"]
body:
    - type: markdown
      attributes:
          value: "**Share the current and relevant details**"
    - type: textarea
      id: physics-title
      attributes:
          label: The Backstory about your Physics Metaphor
          placeholder: "hint: describe the backstory about your Physics metaphor"
      validations:
          required: true
    - type: textarea
      id: physics-content
      attributes:
          label: The Physics Story!
          placeholder: "hint: This is about how I write my Physics story"
      validations:
          required: true
    - type: input
      id: physics-link
      attributes:
          label: A Physics demo/repos link
          placeholder: "e.g.: https://github.com.com/username/my-repos"
    - type: input
      id: physics-donation-link
      attributes:
          label: PayPal Link for Donation (Physics Storyteller)
          placeholder: "e.g.: https://www.paypal.me/your-paypal-profile-username"
