name: Create Ruby Story
description: Add this story to the list
title: "Your Story Title"
labels: ["metaphore", "ruby"]
assignees: ["darkterminal", "mkubdev"]
body:
    - type: markdown
      attributes:
          value: "**Share the current and relevant details**"
    - type: textarea
      id: ruby-title
      attributes:
          label: The Backstory about your Ruby Metaphor
          placeholder: "hint: describe the backstory about your Ruby metaphor"
      validations:
          required: true
    - type: textarea
      id: ruby-content
      attributes:
          label: The Ruby Story!
          placeholder: "hint: This is about how I write my Ruby story"
      validations:
          required: true
    - type: input
      id: ruby-link
      attributes:
          label: A Ruby demo/repos link
          placeholder: "e.g.: https://github.com.com/username/my-repos"
    - type: input
      id: ruby-donation-link
      attributes:
          label: PayPal Link for Donation (Ruby Storyteller)
          placeholder: "e.g.: https://www.paypal.me/your-paypal-profile-username"
